//CREATE MYSQL OR MARIA_DB DATABASE WITH NAME 'plan_db' 
/* SQL TO CREATE TABLE schemes, COPY BELOW QUERY AND RUN IN MARIA_DB  */

"CREATE TABLE schemes (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
status INT(11),
dept_id VARCHAR(30) NOT NULL,
name_scheme VARCHAR(150) NOT NULL,
category VARCHAR(50) NOT NULL,
fund_cat VARCHAR(50) NOT NULL,
budget_est DOUBLE NOT NULL,
pre_budget_est DOUBLE NOT NULL,
pre_revised_est DOUBLE NOT NULL,
FY VARCHAR(50) NOT NULL

)";

/*COPY BELOW QUERY AND RUN THIS IN MARIA_DB */


//FOR CREATING TABLE users

 "CREATE TABLE users (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dept_id VARCHAR(50) NOT NULL,
u_name VARCHAR(50) NOT NULL,
pass VARCHAR(20) NOT NULL,
role VARCHAR(11) NOT NULL,
Mobile_no VARCHAR(12) NOT NULL,
name VARCHAR(30) NOT NULL

)";


